const looks=[
 {name:'Вельвет и шёлк',sub:'Зелёный вельвет · молочный шёлк',photo:'c',tags:['work','office'],status:'сохранён',rating:['5','5','5','4']},
 {name:'Чёрный миди',sub:'Экошуба · сатиновая юбка',photo:'a',tags:['evening','favorite'],status:'♥ любимый',rating:['5','5','5','3']},
 {name:'Красный костюм',sub:'Костюм · чёрный топ',photo:'b',tags:['work','meeting','favorite'],status:'сильный образ',rating:['5','5','5','4']},
 {name:'Шоколадная линия',sub:'Брюки · мягкий трикотаж',photo:'d',tags:['work','office'],status:'на каждый день',rating:['4','5','5','5']},
 {name:'Зелёный акцент',sub:'Пальто · прямые джинсы',photo:'c',tags:['weekend'],status:'хочу примерить',rating:['4','5','4','5']},
 {name:'Сатиновый вечер',sub:'Юбка миди · жакет',photo:'a',tags:['evening','meeting'],status:'♥ любимый',rating:['5','5','5','3']}
];
const items=[
 {name:'Чёрная экошуба',meta:'верхняя одежда · зима',cat:'outerwear',color:'#191716'}, {name:'Вельветовые брюки',meta:'низ · осень',cat:'bottom',color:'#274232',bottom:true},
 {name:'Сатиновая миди-юбка',meta:'юбки · круглый год',cat:'dress',color:'#5c1e30',bottom:true}, {name:'Структурный жакет',meta:'жакеты · круглый год',cat:'tailoring',color:'#453027'},
 {name:'Широкие джинсы',meta:'низ · круглый год',cat:'bottom',color:'#456078',bottom:true}, {name:'Красный костюм',meta:'жакеты · осень',cat:'tailoring',color:'#742033'},
 {name:'Зелёное пальто',meta:'верхняя одежда · осень',cat:'outerwear',color:'#315140'}, {name:'Коричневые брюки',meta:'низ · осень',cat:'bottom',color:'#573729',bottom:true}
];
const wishes=[['Бордовые туфли-лодочки','Соединят красный костюм, сатиновые юбки и тёмные джинсы.','#681f32','+ 4 образа'],['Тонкий топ с открытой линией плеч','Добавит мягкой сексуальности под жакеты и к миди.','#171514','+ 3 образа'],['Молочная рубашка свободного кроя','Сделает вельвет, коричневые брюки и джинсы более собранными.','#eee7da','+ 5 образов']];
const card=l=>`<article class="look-card"><div class="look-photo ${l.photo}"></div><span class="card-status">${l.status}</span><div class="look-card-body"><h3>${l.name}</h3><p>${l.sub}</p></div></article>`;
function renderLooks(filter='all'){document.querySelector('#lookGrid').innerHTML=looks.filter(l=>filter==='all'||l.tags.includes(filter)).map((l,i)=>`<article class="look-card" data-look="${i}"><div class="look-photo ${l.photo}"></div><span class="card-status">${l.status}</span><div class="look-card-body"><h3>${l.name}</h3><p>${l.sub}</p></div></article>`).join('')}
function renderItems(filter='all'){document.querySelector('#closetGrid').innerHTML=items.filter(i=>filter==='all'||i.cat===filter).map((i,index)=>`<article class="item-card" data-item="${index}"><div class="item-image ${i.bottom?'bottom':''}"><i class="garment" style="--color:${i.color}"></i></div><h3>${i.name}</h3><p>${i.meta}</p></article>`).join('')}
document.querySelector('#quickLooks').innerHTML=looks.slice(0,3).map(card).join('');renderLooks();renderItems();
document.querySelector('#wishlistList').innerHTML=wishes.map(w=>`<article class="wish"><div class="wish-visual" style="--color:${w[2]}"></div><div><h3>${w[0]}</h3><p>${w[1]}</p></div><span class="wish-badge">${w[3]}</span></article>`).join('');
function activate(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)activate(nav.dataset.view);const target=e.target.closest('[data-view-target]');if(target)activate(target.dataset.viewTarget);const chip=e.target.closest('#lookFilters .chip');if(chip){document.querySelectorAll('#lookFilters .chip').forEach(x=>x.classList.toggle('active',x===chip));renderLooks(chip.dataset.filter)}const closet=e.target.closest('#closetFilters .chip');if(closet){document.querySelectorAll('#closetFilters .chip').forEach(x=>x.classList.toggle('active',x===closet));renderItems(closet.dataset.filter)}const occasion=e.target.closest('#occasionRow .pill');if(occasion){document.querySelectorAll('#occasionRow .pill').forEach(x=>x.classList.toggle('selected',x===occasion));const map={office:0,meeting:2,weekend:4,evening:1};openLook(looks[map[occasion.dataset.occasion]])}const look=e.target.closest('[data-look]');if(look)openLook(looks[look.dataset.look]);const item=e.target.closest('[data-item]');if(item)openItem(items[item.dataset.item]);if(e.target.closest('.close-dialog'))detail.close()});
const detail=document.querySelector('#detailDialog');function openLook(l){document.querySelector('#dialogContent').innerHTML=`<div class="dialog-wrap"><div class="look-photo ${l.photo}"></div><div class="dialog-copy"><p class="eyebrow">СОХРАНЁННЫЙ ОБРАЗ</p><h2>${l.name}</h2><p>${l.sub}</p><div class="ratings"><div class="rating"><span>Идёт мне</span><b>${'●'.repeat(l.rating[0])}</b></div><div class="rating"><span>Актуально 2026</span><b>${'●'.repeat(l.rating[1])}</b></div><div class="rating"><span>Это моё</span><b>${'●'.repeat(l.rating[2])}</b></div><div class="rating"><span>Практичность</span><b>${'●'.repeat(l.rating[3])}</b></div></div><p class="related">Нажми на любую вещь в гардеробе, чтобы увидеть все образы с ней.</p></div></div>`;detail.showModal()}function openItem(i){document.querySelector('#dialogContent').innerHTML=`<div class="dialog-wrap"><div class="item-image ${i.bottom?'bottom':''}"><i class="garment" style="--color:${i.color}"></i></div><div class="dialog-copy"><p class="eyebrow">ВЕЩЬ В ГАРДЕРОБЕ</p><h2>${i.name}</h2><p>${i.meta}</p><div class="ratings"><div class="rating"><span>Статус</span><b>ОСТАВИТЬ</b></div><div class="rating"><span>Сезон</span><b>ОСЕНЬ</b></div></div><p class="related">Сочетается с: молочным шёлком, сатиновой миди и структурным жакетом.<br><br>В образах: 3</p></div></div>`;detail.showModal()}
looks.forEach((look,index)=>{look.photo=`real-${index%4+1}`});
looks[0].name='Золотой акцент'; looks[0].sub='Твой образ · архив';
looks[1].name='Сатин и шоколад'; looks[1].sub='Твой образ · архив';
looks[2].name='Красный костюм'; looks[2].sub='Твой образ · архив';
looks[3].name='Молочный жакет'; looks[3].sub='Твой образ · архив';
document.querySelector('#quickLooks').innerHTML=looks.slice(0,3).map(card).join('');
renderLooks();
